# List Vs NumPy array

In [1]:
# heights in inch
heights=[74,73,90,71,69]
heights

[74, 73, 90, 71, 69]

In [2]:
#try to convert into cm by multiplying 2.54
heights * 2.54 
# you will get error and the alternate solution is to loop through the list and multiply it

TypeError: can't multiply sequence by non-int of type 'float'

In [3]:
# to solve it we can use numpy array
import numpy as np

In [4]:
np_heights = np.array([74,73,90,71,69])
np_heights

array([74, 73, 90, 71, 69])

In [6]:
type(np_heights)

numpy.ndarray

In [7]:
np_heights * 2.54

array([187.96, 185.42, 228.6 , 180.34, 175.26])

# NumPy comes with its own set of methods and operations

In [8]:
# Merging list 
list_1 = [1,2,3]
list_2 = [4,5,6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [9]:
# by numpy it sums the element 
np_list_1 = np.array([1,2,3])
np_list_2 = np.array([4,5,6])
np_list_1 + np_list_2

array([5, 7, 9])

# Working with N-D Array

In [10]:
arr = np.array([1.0, 2, 3.5, 0.2, True])
print(arr)

[1.  2.  3.5 0.2 1. ]


In [11]:
type(arr)

numpy.ndarray